// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $accessibility from "./routes/accessibility.tsx";
import * as $alerts from "./routes/alerts.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $border from "./routes/border.tsx";
import * as $buttons from "./routes/buttons.tsx";
import * as $cards from "./routes/cards.tsx";
import * as $color from "./routes/color.tsx";
import * as $data_display from "./routes/data-display.tsx";
import * as $feedback from "./routes/feedback.tsx";
import * as $form_patterns from "./routes/form-patterns.tsx";
import * as $forms from "./routes/forms.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $layouts from "./routes/layouts.tsx";
import * as $login from "./routes/login.tsx";
import * as $modals from "./routes/modals.tsx";
import * as $navigation from "./routes/navigation.tsx";
import * as $overview from "./routes/overview.tsx";
import * as $responsive from "./routes/responsive.tsx";
import * as $shadow from "./routes/shadow.tsx";
import * as $spacing from "./routes/spacing.tsx";
import * as $style_guide from "./routes/style-guide.tsx";
import * as $tables from "./routes/tables.tsx";
import * as $tabs from "./routes/tabs.tsx";
import * as $tooltips from "./routes/tooltips.tsx";
import * as $typography from "./routes/typography.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $ProfileDropdown from "./islands/ProfileDropdown.tsx";
import * as $i18n_provider from "./islands/i18n-provider.tsx";
import * as $language_switcher from "./islands/language-switcher.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/accessibility.tsx": $accessibility,
    "./routes/alerts.tsx": $alerts,
    "./routes/api/joke.ts": $api_joke,
    "./routes/border.tsx": $border,
    "./routes/buttons.tsx": $buttons,
    "./routes/cards.tsx": $cards,
    "./routes/color.tsx": $color,
    "./routes/data-display.tsx": $data_display,
    "./routes/feedback.tsx": $feedback,
    "./routes/form-patterns.tsx": $form_patterns,
    "./routes/forms.tsx": $forms,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/layouts.tsx": $layouts,
    "./routes/login.tsx": $login,
    "./routes/modals.tsx": $modals,
    "./routes/navigation.tsx": $navigation,
    "./routes/overview.tsx": $overview,
    "./routes/responsive.tsx": $responsive,
    "./routes/shadow.tsx": $shadow,
    "./routes/spacing.tsx": $spacing,
    "./routes/style-guide.tsx": $style_guide,
    "./routes/tables.tsx": $tables,
    "./routes/tabs.tsx": $tabs,
    "./routes/tooltips.tsx": $tooltips,
    "./routes/typography.tsx": $typography,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/ProfileDropdown.tsx": $ProfileDropdown,
    "./islands/i18n-provider.tsx": $i18n_provider,
    "./islands/language-switcher.tsx": $language_switcher,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
